version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=BitespeedTask!
      - POSTGRES_DB=bitespeed
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
